# Generated by Django 5.1.7 on 2025-03-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="notifications",
        ),
        migrations.AddField(
            model_name="customuser",
            name="expense_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="packing_list_reminders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="trip_invitations",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="voting_polls",
            field=models.BooleanField(default=True),
        ),
    ]
