# Generated by Django 5.1.7 on 2025-04-14 22:55

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0003_pendinguser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=utils.upload_paths.upload_path
            ),
        ),
    ]
