# Generated by Django 5.1.7 on 2025-06-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0005_notification_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
