# Generated by Django 5.1.7 on 2025-10-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0007_userpreferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("friend_request", "Friend Request"),
                    ("friend_accept", "Friend Request Accepted"),
                    ("trip_invite", "Trip Invitation"),
                    ("trip_update", "Trip Update"),
                    ("expense_update", "Expense Update"),
                    ("document_added", "Document Added"),
                    ("packing_added", "Packing Item Added"),
                ],
                max_length=20,
            ),
        ),
    ]
