# Generated by Django 5.1.7 on 2025-11-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0008_alter_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendinguser",
            name="otp",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
        migrations.AlterField(
            model_name="pendinguser",
            name="password",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
