# Generated by Django 5.1.7 on 2025-04-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_stageelement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageelement',
            name='image',
        ),
        migrations.AddField(
            model_name='stageelement',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stageelement',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
