# Generated by Django 5.1.7 on 2025-04-28 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_remove_stageelement_image_stageelement_dislikes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageElementReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.stageelement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stageelement',
            name='user_reactions',
            field=models.ManyToManyField(blank=True, related_name='stage_element_reactions', through='trip.StageElementReaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
