# Generated by Django 5.1.7 on 2025-05-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_squashed_0004_stageelementreaction_stageelement_user_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageelement',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='stageelement',
            name='likes',
        ),
        migrations.AddField(
            model_name='stageelement',
            name='averageReaction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageelementreaction',
            name='reaction',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
