# Generated by Django 5.1.7 on 2025-08-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0011_alter_expense_id_alter_expenseshare_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itineraryevent",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
