# Generated by Django 5.1.7 on 2025-10-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0013_tripmappin_tripmapsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripmappin",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
