# Generated by Django 5.1.7 on 2025-10-31 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip", "0014_tripmappin_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripmappin",
            name="itinerary_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="map_pins",
                to="trip.itineraryevent",
            ),
        ),
        migrations.CreateModel(
            name="MapSpawnPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this location (e.g., 'Hotel', 'Airport', 'Downtown')",
                        max_length=255,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "zoom",
                    models.PositiveIntegerField(
                        default=12, help_text="Zoom level for this spawn point"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for displaying spawn points"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_spawn_points",
                        to="trip.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["trip", "order", "name"],
            },
        ),
    ]
