on:
  pull_request:
    paths:
      - 'server/**.py'
  push:
    branches:
      - main

env:
  BLACK_OPTIONS: "--line-length 88 --check"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install black flake8

      - name: Run Black
        run: black $BLACK_OPTIONS .

      - name: Run Flake8
        run: flake8 backend --max-line-length 88